blank_issues_enabled: false
contact_links:
  - name: 📋 Roadmap
    url: https://github.com/Stuhlsen/training-dashboard/blob/main/README.md#roadmap
    about: Geplante Features und Verbesserungen in der README
